Task_training:
  LEARNING_RATE: 0.00005 
  BATCH_SIZE: 8
  DEVICE: "cpu"
  NUM_EPOCHS: 30
  IMAGE_HEIGHT: 256
  IMAGE_WIDTH: 256
  PIN_MEMORY: true
  NUM_FOLDS: 5
  PATIENCE: 5
  NUM_WORKERS: 0
  LOAD_MODEL: false
  WEIGHT_DECAY: 0.001
  SEED: 2004
dataset:
  root_dir: "D:/work/WBC_Segmentation/WhileBloodCellClassification/data/ClassificationData"
Encoder_lr:
  weight: 0.5
temperature: 
  weight: 0.5
Training_Configuration:
  RESUME_TRAINING: True
  CHECKPOINT_PATH: "/PBC_dataset_split/MyDrive/Colab Notebooks/checkpoint_epoch_6.pth"

PRETRAIN_PARAMETERS:
  PATH: "/PBC_dataset_split/MyDrive/Colab Notebooks/checkpoint_epoch_6.pth"
