Domain_Adaptation_training:
  LEARNING_RATE: 0.0002
  BATCH_SIZE: 8
  DEVICE: "cuda"
  NUM_EPOCHS: 30
  IMAGE_HEIGHT: 256
  IMAGE_WIDTH: 256
  PIN_MEMORY: true
  NUM_WORKERS: 0
  LOAD_MODEL: false
  WEIGHT_DECAY: 0.001
  SEED: 140
dataset:
  root_dir: "D:/work/WBC_Segmentation/WhileBloodCellClassification/data/SourceData"
  mask_dir: "Dataset"
weight:
  weight_cross_entropy: 1
  weight_mask: 2
  weight_rec: 2
  weight_boundary: 2
class_weights:
  background: 1.0
  cytoplasm: 8.0
  nucleus: 4.0
temperature: 
  weight: 0.5
Training_Configuration:
  RESUME_TRAINING: True
  CHECKPOINT_PATH: "D:/work/WBC_Segmentation/WhileBloodCellClassification/logs/Domain_Adaptation_training/exp_20260701_010455/model_epoch_15.pth"
  PRETRAINED_WEIGHTS_PATH: "D:/work/WBC_Segmentation/WhileBloodCellClassification/logs/Domain_Adaptation_training/exp_20260701_010455/model_epoch_15.pth"